GET http://localhost:5109/games

###

GET http://localhost:5109/games/1


###
POST http://localhost:5109/games
Content-Type: application/json



{
  "name" : "Halo: Combat Evolved",
   "genreId": 1,
   "price": 29.99,
   "releaseDate": "2001-11-15"

}


###
PUT http://localhost:5109/games/5
Content-Type: application/json

 {
    "id": 1,
   
    "genre": "Platformer",
    "price": 30,
    "releaseDate": "1985-09-13"
  }

###
DELETE http://localhost:5109/games/5

  







