GET http://localhost:5109/games

###

GET http://localhost:5109/games/1


###
POST http://localhost:5109/games
Content-Type: application/json

{
  "Title": "MineCraft",
  "Genre": "Kids and family",
  "Price": 119.99,
  "ReleaseDate": "2011-11-18"
}


###
PUT http://localhost:5109/games/5
Content-Type: application/json

 {
    "id": 1,
   
    "genre": "Platformer",
    "price": 30,
    "releaseDate": "1985-09-13"
  }

###
DELETE http://localhost:5109/games/5

  







